### PR TITLE
Check if psbt is final, before broadcasting

### LINKED ISSUE #97: Broadcast should tell user to finalize PSBTs
When trying to `broadcast` a PSBT such as
```
cHNidP8BAHEBAAAAAQU2MK4mbnsx/zjbmKwHGUAMVT1zXRFTPBArkMACRZjxAQAAAAD9////AhAnAAAAAAAAFgAU/52lZ+YvMOqGVPodX71HvvjjvhP7FQEAAAAAABYAFKqBwKFeT43famR0JJGaAhoMZKrXAAAAAAABAN4BAAAAAAEBArVvNyXe4TvWObt2vPpIv4IJPeFG1hRK8RtTgzVx3MEAAAAAAP3///8CECcAAAAAAAAWABT/naVn5i8w6oZU+h1fvUe++OO+E+ZAAQAAAAAAFgAUvv5IaH57cUVjoZ35bLxinO1BwkwCRzBEAiABTG7xfKRyZF2ezFCByBLSMGTA2FXYpMN881YXQZB/TgIgbU/OqbuWbe4KhWnjKeglVbnkko70H6glFe/zoo069fUBIQIeb6icGFSB9miQOCV9IMVmJdbEkXG8Hi86LaEyJRa5swAAAAABAR/mQAEAAAAAABYAFL7+SGh+e3FFY6Gd+Wy8YpztQcJMIgICZNLhaTjDm6k30vM/U2+d1TKQ02pk3MFxixFp4EQN1G5IMEUCIQCYRpRlO8YiUXZHLRYmS7fxhgCCDtYRVJ7Tb1rVOKqsHAIgcAeg6Dh8l2N9cixRUyCKwe0jWC9Xc7lNMrxJnDnlmN8BAQMEAQAAACIGAmTS4Wk4w5upN9LzP1NvndUykNNqZNzBcYsRaeBEDdRuGCrNFF1UAACAAQAAgAAAAIABAAAAAQAAAAAAIgIDRcB4bLvY45WvIPqto3nRP4nAQm1FHeIBWcqo2UiIHYoYKs0UXVQAAIABAACAAAAAgAEAAAACAAAAAA==
```
the transaction gets (rightfully) rejected by the network
```
[2022-05-26T13:05:29Z ERROR bdk_cli] Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-mandatory-script-verify-flag (Witness program hash mismatch)\"}")))
```
due to not being `finalize`d.

To avoid user confusion I think the user should be either instructed to finalize the PSBT or have this be done automatically (which would be in line with what other wallets are doing).

### PR DESCRIPTION
**Pull request by rajarshimaitra**
### Description

Fixes #97

Add a finalizer check before broadcasting psbts. 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
While I was manually testing I ran into some issues and in the process of making a unit test I ended up rewriting the logic. If this looks OK to you feel free to pull in the commit, or I can push it into your branch. https://github.com/notmandatory/bdk-cli/commit/304e3b9274bd587a3cf19b4c15fd82b503e904a5

**Comment by rajarshimaitra** [comment]
Yes I briefly checked the logic and looks better than before.. Better to check for malformation also.. Like that you also included tests.. Thanks for this.. Feel free to push it on top of this PR and I will test it out too.. Or we can create a new PR closing this one.. Anything works..

**Comment by notmandatory** [comment]
Sounds good I'll push it to your branch and also do a rebase on `master` branch.

**Review by notmandatory — APPROVED** [review]
tACK 110be3fcfe0a562038791c7faf30a6684db6bc87

**Pull request merged**
