### PR TITLE
Fetch address index in verbose mode for get_new_address

### LINKED ISSUE #40: Feature request: address index in verbose output
Would love to be able to tell the address index on the `get_new_address` method if a verbose flag was enabled!

### PR DESCRIPTION
**Pull request by rajarshimaitra**
### Description

Fixes #40 

cc @thunderbiscuit 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature
* [ ] I've updated `CHANGELOG.md`

### CODE REVIEW

**Comment by rajarshimaitra** [comment]
@notmandatory does this requires changelog update?

**Comment by thunderbiscuit** [comment]
tested ACK [73a9824](https://github.com/bitcoindevkit/bdk-cli/pull/77/commits/73a9824b79d75d9e394cdbb8f9c9ab00e3bca788).

**Comment by thunderbiscuit** [comment]
Related but not related question: I think the verbose flag is not available in the repl. Is that something we could enable?

**Comment by rajarshimaitra** [comment]
I haven't tried yet but it from the code it seems verbose mode should be available to repl too..

**Comment by thunderbiscuit** [comment]
You're right. Took me a minute to figure it out, but my mistake was trying to call `--verbose` _inside_ the repl (which throws an error). Instead the `--verbose` flag needs to be enabled when entering the repl, and will be "on" for all commands inside the loop.

Thanks!

**Review by notmandatory — APPROVED** [review]
ACK 73a9824b79d75d9e394cdbb8f9c9ab00e3bca788

This one is OK without a changelog message, it doesn't break anything. But I might add one when we do the release.

**Pull request merged**
