### PR TITLE
Unleash the power of Bitcoin Core into bdk-cli

### LINKED ISSUE #62: Create Integration tests for bdk-cli
After Proof of Reserves capability is merged in https://github.com/bitcoindevkit/bdk/commit/b2ac4a0dfd33e1286059d0bd090fd9137e2545ba, its time we require some integration tests in the library. Not only for Proof of Reserves functionality, but in general wallet functions too.

This then can be added into CI tests to give us better reliability on the underlying bdk functions.

[electrsd](https://github.com/RCasatta/electrsd) can be used similarly to the bdk test framework to simulate a electrum and bitcoin core backend. https://github.com/bitcoindevkit/bdk/blob/64e88f0e006c68315142d53dc35b633327dde4b5/src/testutils/blockchain_tests.rs#L19-L22

### LINKED ISSUE #76: Open up rpc control for auto deployed regtest mode
The work needs to be done in two parts: 
 - Create non tmp datadir for regtest node data in `~/.bdk-bitcoin`.
 - Open up basic rpc calls via repl commands to do basic node operations.

### PR DESCRIPTION
**Pull request by rajarshimaitra**
### Description

fixes #62 
fixes #76 

This PR does the following
 - Bump bdk version to 0.19. 
 - Opens up some basic bitcoin-core commands via a new sub-command `bdk-cli node <command> [<args>]`. The API of the `node` commands are kept very similar to `bitcoin-cli` api. This allows us to control the auto deployed backend node via `regtest-*` features from bdk-cli itself.
 - The Integration tests are written with `std::Command` from rust. That can be used to simulate various wallet transaction situations with bdk-cli, like #87.
 - These apis are also exposed in `repl` mode so now bdk-cli can have real time communication between a backend and a wallet in repl shell itself. Which can be very useful for quick runs of different testing conditions. 

### Notes to the reviewers

@sandipndev @krtk6160. This is the PR you guys can start working on top of to simulate the intended test situations. At least with `bitcoind` it can be done with all existing toolings. For LND some other wrapper needes to be built.

@notmandatory let me know what you think about the whole framework. 

Also looking for more integration test ideas too add into.

basic `node` usage looks like this
```
$ ./target/debug/bdk-cli node --help
bdk-cli-node 0.5.0
Regtest Node mode

USAGE:
    bdk-cli node <SUBCOMMAND>

FLAGS:
    -h, --help       
            Prints help information

    -V, --version    
            Prints version information


SUBCOMMANDS:
    generate         Generate blocks
    getbalance       Get Wallet balance
    getinfo          Get info
    getnewaddress    Get new address from node's test wallet
    help             Prints this message or the help of the given subcommand(s)
    sendtoaddress    Send to an external wallet address
```

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature
* [x] I've updated `CHANGELOG.md`

### CODE REVIEW

**Comment by notmandatory** [comment]
Hey @rajarshimaitra concept ACK! but I need to focus on the next bdk release (taproot!) so won't be able to do a through review until that's out.

**Comment by rajarshimaitra** [comment]
Ya thanks @notmandatory no issues.. I opened this early for discussion.. This can wait till other major things are done..

**Comment by rajarshimaitra** [comment]
- Done some major refactoring.
 - Updated all the pending dependencies.
 - Updated to `bdk v0.19.0`
 - Broken down the commits into smaller chunks for easier review
 - Refactored the existing `Backend` struct
 - `Backend` now can be both `bitcoind` and `electrum`
 - Some minor update in the integration testing..

**Comment by rajarshimaitra** [comment]
Updated the PR doc.. 

The current test failure at `cargo build --features reserves,electrum --locked` fixes with https://github.com/weareseba/bdk-reserves/pull/5

**Comment by rajarshimaitra** [comment]
Opened an alternate version of the same PR in #102.

Not closing this one yet, in case we need to revert back to previous crate structure..

**Comment by rajarshimaitra** [comment]
Closing this as we are moving ahead with #102

**Pull request closed without merging**
